### ISSUE TITLE
Do you consider this module production ready?

### ISSUE THREAD

**Issue by renannprado** [webauthn4j/keycloak-webauthn-authenticator#30]
In the readme I've found that you call this implementation a [**prototype**](https://github.com/webauthn4j/keycloak-webauthn-authenticator#overview). And since I'd be interested in using it, I'd like to know if the maintainers consider it production-ready. Before attempting using this one in prod.

Thanks!

**Comment by tnorimat** [comment]
@renannprado 
As you mentioned, this project is merely a prototype. I think keycloak's maintainer does NOT consider it production-ready.

I've been trying to implement webauthn's support onto keycloak but I have not used this protype's codes directly.

FYI, the first phase of the webauth's support based on this repository has been merged into keycloak master. Therefore, this project will not be actively maintained basically.

**Comment by renannprado** [comment]
@tnorimat Ah, I see. Thanks for the information!

Now I have two questions:
1. Is there anywhere a documentation about features that were merged so far? 
2. Do you have information about the target version when they expect webauthn (full-featured) to be available? Sorry if I'm asking the wrong person.

**Comment by tnorimat** [comment]
@renannprado Hello.

>1. Is there anywhere a documentation about features that were merged so far?

Please refer to https://github.com/keycloak/keycloak-documentation/blob/master/server_admin/topics/authentication/webauthn.adoc

This is the manual for the webauthn feature that has already been mereged in to the current master branch.

Also this merged webauthn feature has been developed along with the design document. Please look at https://github.com/keycloak/keycloak-community/blob/master/design/web-authn-authenticator.md (but there are some difference between this document and the implementation of the merged PR, I'd like to update it).

>2. Do you have information about the target version when they expect webauthn (full-featured) to be available? Sorry if I'm asking the wrong person.

I'm sorry I don't know it. I am merely a contributor of this webauthn feature. It might be better to ask this question to the keycloak maintainers. Keycloak project has the [mailing list](https://lists.jboss.org/mailman/listinfo/keycloak-user).

**Comment by renannprado** [comment]
Thanks a lot for your time :)
